---
- name: Upgrade system and install Docker & Docker Compose
  hosts: all
  become: true

  vars:
    docker_compose_version: "2.24.4"  # You can change this version
    docker_users:
      - "azureuser"

  tasks:

    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: install git
      apt:
        name: git
        state: present
    
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    
    - name: install make
      apt:
        name: make
        state: present
    
    - name: Add user to docker group
      ansible.builtin.user:
        name: azureuser
        groups: docker
        append: true
        
    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
    
    - name: Include external variables
      include_vars: vars.yml

    - name: Clone private GitHub repository
      git:
        repo: "https://{{ github_token }}@github.com/aaitbelh/inception_bonus.git"
        dest: /home/azureuser/inception

    - name: Ensure required directories exist for Docker volumes
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      loop:
        - "/home/{{ ansible_user }}/data/wp"
        - "/home/{{ ansible_user }}/data/mariadb"
      
    - name : run makefile
      command: make
      args:
        chdir: /home/azureuser/inception
        

