version : '3.8'
services:
  ng:
    depends_on:
      - wp
      - adm
      - pf
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - myOwnNetwork
    restart: always
  wp:
    depends_on:
      - db
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html:rw
    environment:
      - DB_NAME=${DB_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
    networks:
      - myOwnNetwork
    restart: on-failure
  db:
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
    ports:
      - "3306:3306"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
    networks:
      - myOwnNetwork
    volumes:
      - db_data:/var/lib/mysql

networks:
  myOwnNetwork:
    driver: bridge
volumes:
    wp_data:
      driver: 'local'
      driver_opts:
        type: volume
        o: 'bind'
        device: /home/$USER/data/wp
    db_data:
      driver: 'local'
      driver_opts:
        type: none
        o: 'bind'
        device: /home/$USER/data/mariadb
